-- CreateEnum
CREATE TYPE "public"."ActivityMessage" AS ENUM ('EVENT_CREATED', 'EVENT_CREATED_WITH_CLIENT', 'EVENT_UPDATED', 'EVENT_UPDATED_WITH_CLIENT', 'EVENT_DELETED', 'EVENT_DELETED_WITH_CLIENT', 'CLIENT_CREATED', 'CLIENT_UPDATED', 'CLIENT_DELETED', 'SERVICE_PROVIDER_CREATED', 'SERVICE_PROVIDER_UPDATED', 'SERVICE_PROVIDER_DELETED');

-- AlterTable
ALTER TABLE "public"."user_activities" ADD COLUMN     "message_data" TEXT,
ADD COLUMN     "message_type" "public"."ActivityMessage";
